plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "generated/**/*"
    - "spec/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/ParameterLists:
  Max: 7

Layout/LineLength:
  Max: 120

Naming/PredicatePrefix:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false
