AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "generated/**/*"
    - "spec/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Layout/LineLength:
  Max: 120
